name: Build Android APK with Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            python3-pip python3-setuptools python3-wheel python3-venv \
            libncurses5-dev libffi-dev libssl-dev libjpeg-dev zlib1g-dev \
            libfreetype6-dev libbz2-dev libreadline-dev libsqlite3-dev \
            liblzma-dev libgdbm-dev libncursesw5-dev \
            build-essential git unzip curl wget openjdk-17-jdk

      - name: Install Cython and Required Python Packages
        run: |
          python3 -m pip install --upgrade pip
          pip install cython virtualenv buildozer

      - name: Install Android SDK and NDK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk-tools.zip
          unzip -d $ANDROID_SDK_ROOT/cmdline-tools sdk-tools.zip
          rm sdk-tools.zip
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          echo "export ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/35.0.0:$PATH" >> $GITHUB_ENV
          echo "export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Accept Android SDK Licenses
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android Build Tools, Platform Tools & AIDL
        run: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "build-tools;35.0.0" "cmdline-tools;latest"
          export PATH=$ANDROID_SDK_ROOT/build-tools/35.0.0:$PATH
          source $GITHUB_ENV
          which aidl || echo "AIDL still not found!"

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
