name: Build APK

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-venv
          pip install --upgrade pip
          pip install cython buildozer
      
      - name: Install Android SDK and accept licenses
        run: |
          sudo mkdir -p /opt/android-sdk/cmdline-tools
          sudo wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          sudo unzip -q cmdline-tools.zip -d /opt/android-sdk/cmdline-tools
          sudo mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest
          rm cmdline-tools.zip
          export ANDROID_HOME=/opt/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      
      - name: Build APK
        run: |
          export ANDROID_HOME=/opt/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
