name: Build APK with Buildozer (Ubuntu)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-venv \
                              zip unzip openjdk-17-jdk adb \
                              libncurses5-dev curl wget git
          pip install --upgrade pip
          pip install cython buildozer
      
      - name: Install Android SDK & Accept Licenses
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/35.0.0:$PATH
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip
          mv cmdline-tools latest
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;35.0.0" "cmdline-tools;latest"

      - name: Initialize & Configure Buildozer
        run: |
          buildozer init
          sed -i 's/python3/python3.8/' buildozer.spec
          echo "version = 1.0.0" >> buildozer.spec
          echo "source.dir = ." >> buildozer.spec
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
