name: Build APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          aapt openjdk-17-jdk autoconf automake libtool pkg-config zlib1g-dev \
          libncurses5-dev curl unzip git python3-pip python3-setuptools python3-wheel
        pip install --upgrade pip
        pip install cython buildozer

    - name: Install Android SDK & Build Tools
      run: |
        sudo mkdir -p /usr/local/lib/android/sdk
        curl -fo sdk-tools-linux.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        sudo unzip sdk-tools-linux.zip -d /usr/local/lib/android/sdk
        sudo mv /usr/local/lib/android/sdk/cmdline-tools /usr/local/lib/android/sdk/tools
        export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
        export PATH=$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
        yes | sdkmanager --licenses
        sdkmanager --install "platform-tools" "build-tools;33.0.2" "platforms;android-33" "ndk;25.2.9519653"

    - name: Set Environment Variables
      run: |
        echo "export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
        echo "export ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Initialize Buildozer
      run: |
        buildozer init
        sed -i 's/python3/python3.8/' buildozer.spec
        echo "version = 1.0.0" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android debug
